name: Maven Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B clean package -Dmaven.test.skip=true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Construct Docker Tag
      id: docker_tag
      run: |
        # Extract just the repository name (excluding the GitHub username)
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        TIMESTAMP=$(date +%s)
        DOCKER_TAG="${{ secrets.DOCKERHUB_USERNAME }}/${REPO_NAME}:${{ github.run_number }}-$TIMESTAMP"
        echo "Constructed Docker Tag: $DOCKER_TAG"
        echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
        echo "::set-output name=tag::$DOCKER_TAG"

    - name: Build and push
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.docker_tag.outputs.tag }}

  
